name: attendance_with_location
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  pin_code_fields: ^7.4.0
  intl_phone_field: ^3.1.0
  responsive_framework: ^0.2.0
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.8
  firebase_auth: ^3.9.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
